[workspace]
resolver = "2"
members = [
    "ledger-apdu",
    "ledger-transport",
    "ledger-transport-hid",
    "ledger-transport-zemu",
    "ledger-transport-wasm",
    "ledger-zondax-generic",
]

exclude = [
  "examples/wasm"
]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
overflow-checks = true
